- IMPLEMENTATION.md
- INSTALL.md
- README.md
- Vizr.php
- config.json
- example_config.php
- index.php
- js/main.js
- lib/chart_defs.php
- lib/data.php
- lib/main.tmpl
- lib/metadata.php
- lib/permissions.php
- lib/persist.php
- lib/vizr.css
- test/example-ajax-responses.js
- test/main_test.js
- webpack.config.js
This completes the full migration to external modules sans persistence. It still requires the config project, but there's a TODO in the IMPLEMENTATION.md file to update that next.
I did my best to update the documentation so please point out anything that doesn't make sense. Or if I missed anything specific to plugins, exception for the config project part. I'm going to work on that bit next.
`Vizr.php` is the entry point for external modules and is required.
`config.json` defines some metadata, permissions, and the link display. Currently looks like this: https://imgur.com/Pd6Tlqz
I've also updated the vizr `docker-compose.yml`. I'll send another PR for that.
The main work that needed to be done was in `lib/main.tmpl` and `js/main.js`. All of the requires/includes are absolute and the …
> REDDEV-351 external module

- js/chart-form-template.js
- test/chart-form_test.js
Add a prompt option to the date interval <select> to be more consistent with other options and to ensure validation fails at the front end so invalid configuration is not submitted.
> REDDEV-540 Require Selecting Date Interval

- js/chart-form-template.js
- test/chart-form_test.js
Add a prompt option to the date interval <select> to be more consistent with other options and to ensure validation fails at the front end so invalid configuration is not submitted.
> REDDEV-540 Plugin: Require Selecting Date Interval

- test/.eslintrc
- test/bucket_test.js
- test/chart-config_test.js
- test/chart-form_test.js
- test/data-dictionary_test.js
- test/html_test.js
- test/main_test.js
- test/summary-table_test.js
- test/util_test.js
Configure ESLint to know that the tests use Jasmine, removing the need for the `eslint-env` comment.
> ESLint for Tests

- js/main.js
Clears existing event filter dropdown when chart is reloaded.
> REDDEV-530 ; chart reload bug

- js/vue-main.js
- lib/main.tmpl
- webpack.config.js
Inject pid, `canEdit` flag, and asset URLs as in the vanilla JS module.
> Parameter Injection

- js/components/ExampleChart.vue
- js/vue-main.js
- test/components/ExampleChart_test.js
- test/components/Vizr_test.js
Fix broken image in `ExampleChart` component by injecting asset URLs. Resolves #15.
> Fix Broken Image

- config.json
By adding a default `chart-definitions` entry to `project-settings` in `config.json` it allows for the "Module configuration permissions in projects" option when configuring an external module. This matches what was shown in the screenshot attached to the issue. I'm not sure if we need to touch `lib/permissions.php` but figured this would be a start.
> REDDEV-539 project settings

- config.json
The previous definition which produced the configuration option wasn't correct.
This,
```
{
"key": "chart-definitions",
"type": "json-array",
"value": "[]"
}
```
should have been,
```
{
"name": "Chart Definitions",
"key": "chart-definitions",
"type": "json-array"
}
```
however that would allow someone to enter a chart definition manually, and possibly wipe out the entrie set of chart definitions. I'm not sure we want to do that.
I think that drop-down shown in the JIRA issue is what controls permissions for editing the project settings. If that's the case, we may need to leave `lib/permissions.php` as-is. If we want to configure a chart using the project settings, then we may need to define the chart properties in `config.json`. I'm looking into this now but won't have a chance to talk to …
> REDDEV-539 config update

- js/components/Chart.vue
- js/components/ChartSummary.vue
- js/util.js
- test/components/ChartSummary_test.js
- test/components/Chart_test.js
Implement a component that displays the summary tables. Fixes #17.
Now pretty much there visually:
> Chart Summary Component

- js/chart-config.js
- js/components/Chart.vue
- js/main.js
- test/chart-config_test.js
Add an argument to the the functions that construct charts to pass the canvas element to use, rather than searching the DOM for an element with a known ID. Fixes #30.
This is more efficient and enables the use of a ref in the Vue component, which fixes some warnings in the chart component tests.
> Provide Element to Chart Construction

- js/components/ChartForm.vue
- package-lock.json
- package.json
- test/components/ChartForm_test.js
Validate chart form when inputs change and prior to saving.
> Chart Form Validation

- js/components/Chart.vue
- js/components/ChartForm.vue
- js/components/Vizr.vue
- js/services/data-service.js
- test/components/ChartForm_test.js
- test/components/Chart_test.js
- test/components/Vizr_test.js
- test/example-ajax-responses.js
- test/example-chart-def.js
- test/services/data-service_test.js
Implement saving chart configuration when charts are added, updated, and deleted. Fixes #25, #29.
This one is probably best read one commit at a time.
> Persistence

- .babelrc
- js/vue-main.js
- package-lock.json
- package.json
- webpack.config.js
Use `babel-preset-env` to tailor the Babel polyfill, rather than including the whole thing.
> Use babel-preset-env for Polyfill

- js/components/ChartForm.vue
- test/components/ChartForm_test.js
The recursive case of `ChartForm`'s `sanitizeModel` method throws an exception calling `Object.keys` when the input object is null. Fix by checking whether the field value is truthy before recursing.
> Handle Null in sanitizeModel

- README.md
- Vizr.php
- config.json
This reverts to the previous permission model.
A user can only edit charts if they are a super user or have design rights.
For a user to view charts they must have design rights, or have the Vizr
module checked on the User Rights page. For the later, the module must
be configured to 'Require module-specific user privilege'.
> REDDEV-539 removed check for module access

- lib/persist.php
This fixes an issue where users couldn't persist chart definitions. I would have caught this in the last PR had I created a new user. The current bug in REDCap that doesn't remove module specific permissions bit me because my basic user still had module rights from the previous round of testing which can't be removed as of yet. I noticed this method, `disableUserBasedSettingPermissions`, yesterday so it was easy to patch. Removing REDCap's user specific permission model does mean that we now how to manage our own permissions.
> REDDEV-539 save fix

- js/components/ChartForm.vue
- lib/vizr.css
reddev-570 ; Adds back error styling in forms, which was removed in the upgrade from Bootstrap 3 to Bootstrap 4.
> Form error styling

- README.md
Add a warning to the README.md of the Vizr plugin indicating that it has been replaced by an external module.
> Add Warning to Plugin README

- package-lock.json
- package.json
Update the version of jQuery used by the tests to match recent releases of REDCap. This removes a warning about a vulnerable dependency, but it should have no effect in production, because jQuery is marked external in Webpack config.
> Update jQuery For Tests

- lib/chart_defs.php
- lib/data.php
- lib/main.tmpl
- lib/metadata.php
- lib/permissions.php
- lib/persist.php
This fix accomodates instances where the external modules location is
not the default location. When Vizr was a plugin it was dependent on the
`redcap_connect.php` file to be in a known location, but the external
module API automatically provides this file so it can be removed as a
dependency in the PHP files.
> REDDEV-637 Allow non-standard external module locations

- lib/main.tmpl
Because we block the API URL outside OHSU, Vizr fails to load and
results in a blank page. Changing the configuration moves it to use the
the regular REDCap URL with versions.
> REDDEV-654 Vizr blank if using API URL at OHSU

- .github/workflows/test.yml
- package.json
Set up testing with GitHub actions. This will make it easier to tell if dependency updates created by Dependabot will break anything.
> CIS-1224 Test With GitHub Actions

- test/components/ChartForm_test.js
- test/components/Chart_test.js
- test/components/Vizr_test.js
Replace deprecated Vue Test Utils functions with equivalent calls that aren't deprecated. There are still deprecations related to how we're mocking calls to `debounce` that I haven't figured out yet, which will be a subsequent PR.
> Vue Test Deprecations

- .github/workflows/test.yml
Run the Webpack build in CI to catch regressions caused by updates. This should make it easier to decide whether to merge Dependabot updates to build tooling.
> Run Webpack build in CI

- package-lock.json
- package.json
- test/components/ChartForm_test.js
- test/components/ChartSummary_test.js
- test/components/Chart_test.js
- test/components/Vizr_test.js
Update tests to `await` the result of all calls to `trigger`, `setValue`, and `setProps`, as described in the [documentation on testing asynchronous behavior](https://vue-test-utils.vuejs.org/guides/#testing-asynchronous-behavior). Fixes test failures after upgrade to `@vue/test-utils` 1.1.3.
> Async test fixes

- config.json
- js/components/Chart.vue
- js/components/ChartForm.vue
- js/components/Instructions.vue
- js/components/Vizr.vue
- lib/metadata.php
Make changes needed to upgrade to Bootstrap 5, introduced in REDCap 13.4.0:
* Use `data-bs-` attributes for JS integration
* Fix styling of form `<select>` inputs
* Fix styling of calendar input addons
* Bump minimum REDCap version
> REDDEV-749 Upgrade to Bootstrap 5
