js/inline-docs.js, js/main.js, lib/main.tmpl
Add code to construct the URL to the example chart image so it displays correctly.
=> REDDEV-351 Fix Example Chart Image

config.json
Update module metadata as described in REDDEV-533:
* Change name and description
* Add Liz to list of developers
=> REDDEV-533 Update Module Metadata

js/chart-form.js, lib/persist.php, package-lock.json, package.json, test/chart-form_test.js
Sanitize input from the user by doing the following:
* Stripping HTML from input entered via the chart form
* Using `REDCap::filterHTML` on chart configuration when persisting
=> REDDEV-535 Input Sanitization

js/chart-form.js, lib/persist.php, package-lock.json, package.json, test/chart-form_test.js
Backport sanitization fixes from external module to the plugin version of Vizr.
=> Plugin Sanitization

js/main.js
Excludes records with empty date fields from results when selecting by event.
=> REDDEV-542 ; event filter bug

.eslintrc.js, js/components/Chart.vue, js/components/Vizr.vue, js/services/data-service.js, js/vue-main.js, lib/vizr.css, package-lock.json, package.json, test/components/Vizr_test.js, test/example-chart-def.js, test/services/data-service_test.js
Refactor data fetching logic into a separate service and update the Vizr component to fetch metadata and chart configuration when mounted.
=> Project Data Fetching

js/components/Chart.vue, js/components/Vizr.vue, test/components/Chart_test.js
Get the chart component basically working:
* Fetch data for the chart on mount
* Summarize data
* Create chart
Fixes #17.
=> Basic Chart Component

js/components/Chart.vue, js/services/data-service.js, test/components/Chart_test.js, test/example-ajax-responses.js, test/services/data-service_test.js
Validate chart data when it is received by the data service:
* Detect problematic data and collect warnings
* Filter out records with blank date fields
Fixes #26
=> Chart Data Validation

js/components/Chart.vue, js/components/Vizr.vue, test/components/Chart_test.js
Add initial event-handling code to `Chart.vue`.
=> Initial Event Handling

js/components/Chart.vue, test/components/Chart_test.js
Implement the select list for longitudinal charts that include data from multiple events. Fixes #28.
=> Live Event Filter

js/components/Chart.vue, js/components/ChartForm.vue, js/components/Vizr.vue, js/util.js, test/components/ChartForm_test.js, test/util_test.js
Initial chart form component:
* Template and data binding
* Attaches jQuery date pickers on load
* Save / cancel handlers
I apologize for the size of this review. I should have taken this on in smaller increments.
=> Chart Form Component

js/components/ChartForm.vue, js/util.js, test/components/ChartForm_test.js, test/util_test.js
Add support for configuring targets to the `ChartForm` component.
=> Support for Targets

.eslintrc.js, js/components/Chart.vue, js/components/ChartForm.vue, package-lock.json, package.json
Configure ESLint to lint `.vue` single-file component files and fix errors it reported.
=> ESLint Vue Files

js/components/ChartForm.vue, test/components/ChartForm_test.js
Add code to the `ChartForm` component to strip HTML on save. Fixes #43.
=> Strip HTML on Save

Vizr.php, config.json, lib/permissions.php
I haven't been able to fully test this code, but I think it's doing the right thing. If REDCap 8.5.4 or 8.6.0 is released before the end of the sprint maybe one of you can give it a go. Just making sure this code is handed off in case that happens. I still haven't figured out permissions on our local containers so it may have to wait for our dev instance to be upgraded. I was reading through the REDCap docs and wondering if we need to check on the pear modules. Found that here: https://community.projectredcap.org/articles/691/authentication-how-to-change-and-set-up-authentica.html
=> Reddev 539 config update

package.json
Add a development build mode to ease debugging and exploration with Vue devtools.
=> Dev Build Mode

.eslintrc.js, karma.conf.js, package.json, test/.eslintrc, webpack.config.js
Incorporate ESLint improvements from OCTRI/redcap-consort-report#25.
=> ESLint Improvements

package-lock.json, package.json
Update dependencies in response to jQuery CVE.
=> CIS-1014 jQuery CVE Updates

package-lock.json, package.json
Update lodash to address vulnerabilities.
=> CIS-1032 Update Lodash

package-lock.json, package.json
Update webpack and copy-webpack-plugin to patch serialize-javascript XSS vulnerability.
=> Updates for CVE-2019-16769

.dependabot/config.yml
Add Dependabot config file with auto-merge configuration.
=> CIS-1224 Add Dependabot Config File

.github/workflows/test.yml
Use Node.js 14 (latest LTS) to run tests.
=> Test With Node 14

package-lock.json, package.json
Resolve PostCSS vulnerability related to `vue-loader` and install missing PostCSS peer dependency.
=> PostCSS Updates

lib/chart_defs.php, lib/data.php, lib/main.tmpl, lib/metadata.php, lib/permissions.php, lib/persist.php, package-lock.json
Made changes enabling EM to pass the REDCap Security Scanner, and to maintain consistency
* Applied `Octri\Vizr` namespace to PHP files (and template file) producing errors
* Applied `Octri\Vizr` namespace to remaining PHP files for consistency 
* Ensure references to non-module entities fallback to global namespace
=> REDDEV-757 Pass Security Scan
